# Generated by Django 2.1.7 on 2019-02-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodes',
            name='id',
        ),
        migrations.AddField(
            model_name='nodes',
            name='dc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nodes',
            name='node_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nodes',
            name='solution',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='node_IP',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
